using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CRM.Medical.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddComplaints : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Idempotent: database may already have complaints (e.g. created outside EF history).
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS complaints (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "UserId" text NOT NULL,
                    "Title" character varying(500) NOT NULL,
                    "Description" character varying(8000) NOT NULL,
                    "AttachmentUrl" character varying(2048),
                    "Status" character varying(64) NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone,
                    CONSTRAINT "PK_complaints" PRIMARY KEY ("Id")
                );
                """);

            migrationBuilder.Sql(
                """
                DO $EF$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'FK_complaints_users_UserId'
                    ) THEN
                        ALTER TABLE complaints
                        ADD CONSTRAINT "FK_complaints_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE;
                    END IF;
                END $EF$;
                """);

            migrationBuilder.Sql(
                """CREATE INDEX IF NOT EXISTS "IX_complaints_CreatedAt" ON complaints ("CreatedAt");""");

            migrationBuilder.Sql(
                """CREATE INDEX IF NOT EXISTS "IX_complaints_Status" ON complaints ("Status");""");

            migrationBuilder.Sql(
                """CREATE INDEX IF NOT EXISTS "IX_complaints_UserId" ON complaints ("UserId");""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "complaints");
        }
    }
}
